#maggior parte dei domini esistenti (i più utilizzati)
DOMINI = [
    ".com", ".net", ".org", ".info", ".biz", ".online", ".site", ".tech", ".store", ".app",
    ".blog", ".web", ".dev", ".io", ".me", ".co", ".xyz", ".life", ".space", ".cloud",
    ".news", ".media", ".club", ".team", ".today", ".news", ".chat", ".art", ".design",
    ".studio", ".music", ".video", ".photography", ".coffee", ".fashion", ".love", ".vip",
    ".guru", ".ninja", ".pizza", ".dog", ".fun", ".zone", ".world", ".live", ".shop",
    ".digital", ".group", ".social", ".site", ".solutions", ".services", ".agency",
    ".support", ".network", ".systems", ".center", ".expert", ".expertise",
    ".it", ".fr", ".de", ".es", ".uk", ".us", ".ca", ".au", ".ru", ".jp", ".cn", ".br",
    ".mx", ".in", ".nl", ".se", ".ch", ".be", ".dk", ".no", ".pl", ".cz", ".gr", ".ie",
    ".pt", ".za", ".sg", ".hk", ".tw", ".kr", ".at", ".fi", ".hu", ".lt", ".lv", ".ee",
    ".bg", ".ro", ".sk", ".si", ".hr", ".ua", ".by", ".md", ".kz", ".ae", ".sa", ".il",
    ".qa", ".bh", ".om", ".kw", ".eg", ".ng", ".ke", ".tz", ".ug", ".ma", ".dz", ".tn",
    ".eu", ".asia", ".africa", ".lat", ".latino", ".cat", ".bzh", ".scot", ".gal", ".eus",
    ".quebec", ".vlaanderen", ".wales", ".cymru", ".brussels",
    ".edu", ".gov", ".mil", ".museum", ".jobs", ".aero", ".coop", ".travel", ".mobi",
    ".int", ".post", ".tel", ".name", ".pro", ".cat", ".arpa", ".bio", ".bank", ".law",
    ".doctor", ".health", ".insurance", ".lawyer", ".pharmacy", ".restaurant", ".beer",
    ".casino", ".wine", ".movie", ".game", ".software",
    ".academy", ".bargains", ".camera", ".capital", ".care", ".casino", ".charity",
    ".church", ".cleaning", ".click", ".clothing", ".coach", ".coffee", ".community",
    ".company", ".computer", ".construction", ".contractors", ".cool", ".country",
    ".coupons", ".credit", ".cruises", ".dance", ".date", ".dating", ".deal", ".degree",
    ".delivery", ".democrat", ".diamonds", ".diet", ".digital", ".direct", ".directory",
    ".discount", ".diy", ".doctor", ".dog", ".domains", ".education", ".email", ".energy",
    ".engineer", ".engineering", ".enterprises", ".equipment", ".estate", ".events",
    ".exchange", ".expert", ".exposed", ".fail", ".farm", ".finance", ".financial",
    ".fish", ".fishing", ".fitness", ".flights", ".florist", ".football", ".forsale",
    ".foundation", ".fun", ".fund", ".furniture", ".futbol", ".gallery", ".games",
    ".garden", ".gift", ".gifts", ".gives", ".glass", ".global", ".gold", ".golf",
    ".graphics", ".gratis", ".green", ".gripe", ".group", ".guide", ".guitars",
    ".guru", ".hair", ".holdings", ".holiday", ".home", ".homes", ".horse", ".hospital",
    ".host", ".hosting", ".house", ".how", ".immo", ".immobilien", ".industries",
    ".ink", ".institute", ".insurance", ".insure", ".international", ".investments",
    ".jewelry", ".kitchen", ".land", ".lawyer", ".lease", ".legal", ".lgbt", ".life",
    ".lighting", ".limited", ".limo", ".live", ".loan", ".loans", ".london", ".lotto",
    ".love", ".luxury", ".maison", ".management", ".market", ".marketing", ".media",
    ".medical", ".meet", ".melbourne", ".meme", ".menu", ".miami", ".moda", ".mom",
    ".money", ".mortgage", ".motorcycles", ".movie", ".music", ".navy", ".network",
    ".news", ".ninja", ".one", ".online", ".ooo", ".page", ".paris", ".partners",
    ".party", ".pharmacy", ".photo", ".photography", ".photos", ".physio", ".pics",
    ".pictures", ".pizza", ".place", ".plumbing", ".plus", ".poker", ".porn", ".press",
    ".pro", ".productions", ".promo", ".properties", ".property", ".pub", ".qpon",
    ".quest", ".racing", ".radio", ".realestate", ".recipes", ".red", ".rehab",
    ".reise", ".reisen", ".rent", ".rentals", ".repair", ".report", ".republican",
    ".rest", ".restaurant", ".reviews", ".rich", ".rip", ".rocks", ".rodeo", ".room",
    ".ryukyu", ".sale", ".salon", ".sarl", ".school", ".science", ".services",
    ".sex", ".sexy", ".shoes", ".shop", ".shopping", ".show", ".singles", ".site",
    ".ski", ".social", ".software", ".solar", ".solutions", ".space", ".sport",
    ".studio", ".style", ".sucks", ".supplies", ".supply", ".support", ".surf",
    ".surgery", ".systems", ".tattoo", ".tax", ".taxi", ".team", ".tech", ".technology",
    ".tel", ".tennis", ".theater", ".theatre", ".tickets", ".tips", ".tires", ".today",
    ".tools", ".top", ".tours", ".town", ".toys", ".trade", ".training", ".travel",
    ".trust", ".tube", ".tv", ".university", ".vacations", ".vegas", ".ventures",
    ".versicherung", ".vet", ".viajes", ".video", ".villas", ".vision", ".vlaanderen",
    ".vodka", ".vote", ".voting", ".voto", ".voyage", ".watch", ".webcam", ".website",
    ".wed", ".wedding", ".whoswho", ".win", ".work", ".works", ".world", ".wow",
    ".wtf", ".xerox", ".xxx", ".xyz", ".yoga", ".zone"
]